apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: tax-calculator-pipeline-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline

  params:
    - name: ARGS
      value:
        - install

  workspaces:
    - name: source
      emptyDir: {}
