apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: tax-calculator-pipeline-run-
spec:
  pipelineRef:
    name: tax-calculator-pipeline

  workspaces:
    - name: source
      emptyDir: {}
