apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm
spec:
  params:
    - name: ARGS
      type: array
      default:
        - install
  steps:
    - name: npm
      image: node:20
      command:
        - npm
      args: ["$(params.ARGS[*])"]

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jasmine
spec:
  steps:
    - name: jasmine
      image: node:20
      script: |
        #!/usr/bin/env sh
        npm install
        npx jasmine

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: IMAGE
      type: string
      default: us.icr.io/sn-labs-sunehamariam/tax-calculator:latest
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)
        - --destination=$(params.IMAGE)
